plugins:
  - jekyll-paginate
  - jekyll/tagging
  - jekyll-sitemap
  - jekyll-seo-tag
twitter_username: chloeannmurdock
tag_page_dir: tag
instagram_username: chloemurdockk
authors:
  Chloe:
    name: Chloe Murdock
    bio: Intern and college student, majoring in journalism and international
      studies.
    gravatar: null
    email: null
    website: https://chloemurdock.com
    twitter_username: chloeannmurdock
include:
  - _pages
  - _headers
author: chloeannmurdock
logo: null
permalink: pretty
social:
  name: Chloe Murdock
  links:
    - https://twitter.com/chloeannmurdock
    - http://instagram.com/chloemurdockk
    - https://www.facebook.com/chloe.murdock.716
    - https://www.linkedin.com/in/chloe-m-275197133/
sass:
  style: compressed
markdown: kramdown
url: https://chloemurdock.com
defaults:
  - scope:
      path: _pages
    values:
      permalink: /:basename
  - scope:
      path: tag
    values:
      sitemap: false
twitter:
  username: chloeannmurdock
  card: summary
tag_page_layout: tag_page
paginate: 12
tag_permalink_style: pretty
title: Chloe Murdock
exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
email: chloe.murdock@gmail.com
description: This is the homepage of Chloe Murdock, Intern and college student,
  majoring in journalism and international studies and I am dingus
baseurl: ""
