backend:
  name: github
  repo: chloemurdock/chloemurdock.github.io
  branch: master
  site_domain: chloemurdock.netlify.com

media_folder: "images" # Media files will be stored in the repo under images
public_folder: "/images" # The src attribute for uploaded media will begin with /images

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", dateFormat: 'YYYY-MM-DD', timeFormat: 'HH:mm', format: 'YYYY-MM-DD HH:mm'}
      - {label: "Image", name: "image", widget: "image", required: false, hint: 'Use tinypng.com before uploading!'}
      - {label: "Tags", name: "tags", widget: "string", hint: 'Tags are separated by spaces!'}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages/" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{label}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Image", name: "image", widget: "image", required: false}
      #- {label: "Publish Date", name: "date", widget: "datetime"}
      # - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "data"
    label: "Data"
    files:
      - name: "resourcelist"
        label: "Resources"
        file: "_data/resources.yaml"
        fields:
          - name: "resources"
            label: "Resources"
            widget: "list"
            fields:
              - {label: "Type", name: "type", widget: "string"}
              - name: "list"
                label: "List"
                widget: list
                fields:
                  - {label: "Title", name: "title", widget: "string"}
                  - {label: "URL", name: "URL", widget: "string"}